### ISSUE TITLE
Add support for colored screens

### ISSUE THREAD

**Issue by txoof** [txoof/epdlib#1]
3 color screens throw errors when used with this code

**Comment by txoof** [comment]
simple fix is to change how `screen` handles displaying images -- pass an empty 1x1 image when dealing with a colored display.

This won't add color support, but will fix the problem of thrown errors.

**Comment by txoof** [comment]
commit https://github.com/txoof/epdlib/commit/70b168360eee31a5c8f2376118332048796ad674 should resolve this with the added cost of much slower updates.

This can pave the way to adding color output.

**Comment by txoof** [comment]
merge in suggestions from pull request #2

**Comment by txoof** [comment]
Closed with commit https://github.com/txoof/epdlib/commit/7bf3865969cf1e1840cfd4878e220b7344609b5e

**Comment by tmmorin** [comment]
This fix works just fine, thank you !
