### ISSUE TITLE
Right Aligned text should align with right side of TextBlock

### ISSUE THREAD

**Issue by tristanhaeuser** [txoof/epdlib#65]
I'm working on a Waveshare 6'' HD EPD with IT8951 controller. 
When attempting to set up a right-aligned text within a text block I encounter unexpected spacing from the right border. Despite setting no padding and experimenting with various available properties, the issue persists. Additionally, I've noticed that even with left-aligned text, there's an invisible padding that restricts the utilization of the entire screen. This padding is problematic as it prevents optimal use of the display area.
Is this expected behaviour to have a safety margin on the right side or a bug somewhere in the library?

![IMG_4188](https://github.com/txoof/epdlib/assets/82410366/e0a930a4-cafc-4b98-8737-ad2995d9db5a)

```
Section = {
    'text': {
        'type': 'TextBlock',
        'max_lines': 25,
        'align': 'right',
        'padding': 0,
        'width': 1,
        'height': 1,
        'abs_coordinates': (0, 0),
        'hcenter': False,
        'vcenter': True,
        'relative': None,
        'font': sf_font,
        'font_size': None,
        'inverse': False,
        'text_wrap': True,
        'fill': 'White',
        'bkground': 'Black',
        'mode': 'L'
    }
}
```

**Comment by txoof** [comment]
You've probably found a bug. That definitely doesn't look right.
Thanks for providing the layout and font. 

Let me take a poke at this and see if there's something I can do to fix it. 

Would you mind sharing an image for the left-aligned issue as well. 

Just to be certain, is the resolution of your [screen](https://www.waveshare.com/wiki/6inch_HD_e-Paper_HAT) 1448 X 1072?

**Comment by tristanhaeuser** [comment]
Yes, that's correct the resolution is 1448 x 1072. 
Here is an image for the left-aligned issue:

![IMG_4191](https://github.com/txoof/epdlib/assets/82410366/5b901c75-614c-49eb-92bf-cc38afcf91db)

I think the bug is not font-specific. I used a variety of fonts while developing and it doesn't seem like it would make any difference.

**Comment by txoof** [comment]
@tristanhaeuser I'll see if I can fix the justification issue and at least get right justification to shove over to the right side and leave "useless" space on the left instead.

As for distributing text better, I'm open to suggestions. I really struggled to get a solution that worked well for most `TextBlock` sizes. The calculations happen in `[Block.TextBlock](https://github.com/txoof/epdlib/blob/68e9e9eaa6c2ab1084f4fb128488b761f42e9ce4/epdlib/Block.py#L965-L991)`. If you have any ideas how to make this a bit better, I'd love to have some other brains working on it.

Ideally, it would be a bit more dynamic and flow text with the logic of a soft-wrap, but I haven't really thought much about how to do that. I was focused on using the `textwrap` library.

**Comment by txoof** [comment]
looks like `TextBlock` needs an additional case for right aligned text somewhere around [l1087](https://github.com/txoof/epdlib/blob/68e9e9eaa6c2ab1084f4fb128488b761f42e9ce4/epdlib/Block.py#L1087-L1093).

It's too late tonight to figure out the math, but this is the gist:
```
if self.align == 'ralign'
   paste_x = <<insert math here for shoving text to right border>>>
   logging.debug('pasting raligned text on the right side')
```

**Comment by txoof** [comment]
@tristanhaeuser 
I've done some research and I can't find a good alternative to textwrap other than trying to do it from the ground up. 

If you have any ideas, I'd love to hear them. I'm going to dig into your right justification bug shortly and hopefully have a solution this weekend.

**Comment by txoof** [comment]
@tristanhaeuser well, that was easier than I thought!

I've got a fix ready to go, but I'd appreciate it if you could test it out. The output is below. 

You can install the issue-branch with:

`pip install git+https://github.com/txoof/epdlib/epdlib.git@I65_alignment`

![image](https://github.com/txoof/epdlib/assets/14262505/1983af1b-34cd-4c35-a7d2-fdc23eb6cf5c)

**Comment by tristanhaeuser** [comment]
@txoof  Wow, thank you for coming up with a fix so quickly. I'm currently very busy, but I try it out as soon as possible. 
I let you know when I tested it. Should I close this issue?

**Comment by txoof** [comment]
No problem. I hope this resolves your problem. The fix was earlier than I thought.

Leave it open until you've tested. I'll close it when I merge the update.

**Comment by tristanhaeuser** [comment]
@txoof I installed the branch with the fix. As far as I can tell everything works now as expected.  : )

**Comment by txoof** [comment]
Thanks for checking. I'll merge it in when I get a minute and publish to PyPi. 

Don't forget to update your requirements.txt!

**Comment by txoof** [comment]
@tristanhaeuser the v0.6.5 is up on pypi. Happy hacking!

If you find any other issues with this, feel free to reopen the ticket.
