### ISSUE TITLE
Breakpoint in Master Branch

### ISSUE THREAD

**Issue by tristanhaeuser** [txoof/epdlib#67]
There is a breakpoint present in the master branch of the repo. I think it got left behind from debugging. 
It is in [epdlib/Block.py line 1011.](https://github.com/txoof/epdlib/blob/3a49142e0b05cc0d798662a5f5902e4c972189e4/epdlib/Block.py#L1011)

**Comment by txoof** [comment]
@tristanhaeuser Thanks for catching this. Should be OK now.

Corrected in #68
